name: CI
on: [push, pull_request]

jobs:
  unit-tests:
    name: Unit tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: FALSE
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: go build ./cmd/actionlint
      - run: go test -v -race -coverprofile coverage.txt -covermode=atomic
      # Dog fooding 🐶
      - run: ./actionlint
      - uses: codecov/codecov-action@v1
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: go get honnef.co/go/tools/cmd/staticcheck@latest
      - name: Add staticcheck to PATH
        run: echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"
      - run: staticcheck ./...
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'true'
        if: false || true
      - run: echo 'true2'
        if: true && true
      - run: echo 'false'
        if: true && false
